# =====================================================================
# Platform Test Configuration
# =====================================================================
# This file is maintained by the APPLICATION DEVELOPER
# It tells the platform CI/CD pipeline how to run tests for this app
# =====================================================================

app:
  name: "langflow"
  type: "fullstack"  # Options: frontend, backend, fullstack, static, api

# Test Commands (Provided by App Developer)
# ---------------------------------------------------------
tests:
  # Frontend Tests
  frontend:
    enabled: true
    working_directory: "src/frontend"
    setup_commands:
      - "npm ci"
    test_command: "npm test -- --coverage --watchAll=false"
    coverage_threshold: 70
    
  # Backend Tests  
  backend:
    enabled: true
    working_directory: "src/backend"
    setup_commands:
      - "pip install -r requirements.txt"
      - "pip install pytest pytest-cov"
    test_command: "pytest --cov=. --cov-report=xml --cov-fail-under=70"
    coverage_threshold: 70
    
  # Integration Tests (Optional)
  integration:
    enabled: false
    test_command: "docker-compose -f docker-compose.test.yml up --abort-on-container-exit"
    
  # Linting (Optional)
  linting:
    frontend:
      enabled: true
      working_directory: "src/frontend"
      command: "npm run lint"
    backend:
      enabled: true  
      working_directory: "src/backend"
      command: "ruff check ."
      
  # Type Checking (Optional)
  type_checking:
    frontend:
      enabled: true
      working_directory: "src/frontend"
      command: "npm run type-check"
    backend:
      enabled: true
      working_directory: "src/backend" 
      command: "mypy ."

# Build Configuration (Optional overrides)
# ---------------------------------------------------------
build:
  # Dockerfile paths (if different from auto-discovery)
  dockerfiles:
    frontend: "src/frontend/Dockerfile"
    backend: "src/backend/Dockerfile"  # Platform will need to create this
    
  # Build arguments
  build_args:
    frontend: []
    backend: []
    
  # Build context
  context: "."
  
# Environment Variables for Testing
# ---------------------------------------------------------
environment:
  # Common environment variables for all tests
  common:
    NODE_ENV: "test"
    PYTHON_ENV: "test"
    LOG_LEVEL: "debug"
    
  # Frontend-specific environment variables
  frontend:
    VITE_API_URL: "http://localhost:7860"
    VITE_WS_URL: "ws://localhost:7860"
    
  # Backend-specific environment variables  
  backend:
    LANGFLOW_HOST: "0.0.0.0"
    LANGFLOW_PORT: "7860"
    LANGFLOW_LOG_LEVEL: "DEBUG"
    LANGFLOW_DATABASE_URL: "sqlite:///./test.db"
