apiVersion: v2
name: langflow
description: A Helm chart for Langflow - AI-powered agent and workflow builder
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - langflow
  - ai
  - workflow
  - spanda
  - platform
home: https://github.com/langflow-ai/langflow
sources:
  - https://github.com/langflow-ai/langflow
maintainers:
  - name: Platform Team
    email: platform@yourorg.com
